services:
    _defaults:
        autowire: true
        autoconfigure: true


    JanMikes\Slacker\:
        resource: '../src/*'
        exclude: '../src/{SlackerKernel.php,**/Exceptions}'

    JanMikes\Slacker\ExchangeWebService\MailClient:
        arguments:
            $exchangeEmail: '%env(SLACKER_EXCHANGE_EMAIL)%'
            $exchangeUser: '%env(SLACKER_EXCHANGE_USER)%'
            $exchangePassword: '%env(SLACKER_EXCHANGE_PASSWORD)%'
            $messageSender: '%env(SLACKER_MESSAGE_SENDER)%'
            $messageSubject: '%env(SLACKER_MESSAGE_SUBJECT)%'

    JanMikes\Slacker\HttpClient:
        arguments:
            $user: '%env(SLACKER_EXCHANGE_USER)%'
            $password: '%env(SLACKER_EXCHANGE_PASSWORD)%'

    logger:
        class: 'Symfony\Component\HttpKernel\Log\Logger'
        arguments:
            $minLevel: 'info'
