<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerON5E5BD\JanMikes_Slacker_SlackerKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerON5E5BD/JanMikes_Slacker_SlackerKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerON5E5BD.legacy');

    return;
}

if (!\class_exists(JanMikes_Slacker_SlackerKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerON5E5BD\JanMikes_Slacker_SlackerKernelDevDebugContainer::class, JanMikes_Slacker_SlackerKernelDevDebugContainer::class, false);
}

return new \ContainerON5E5BD\JanMikes_Slacker_SlackerKernelDevDebugContainer([
    'container.build_hash' => 'ON5E5BD',
    'container.build_id' => 'a4fd5376',
    'container.build_time' => 1584405139,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerON5E5BD');
