<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerER9Jhtn\JanMikes_Slacker_SlackerKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerER9Jhtn/JanMikes_Slacker_SlackerKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerER9Jhtn.legacy');

    return;
}

if (!\class_exists(JanMikes_Slacker_SlackerKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerER9Jhtn\JanMikes_Slacker_SlackerKernelDevDebugContainer::class, JanMikes_Slacker_SlackerKernelDevDebugContainer::class, false);
}

return new \ContainerER9Jhtn\JanMikes_Slacker_SlackerKernelDevDebugContainer([
    'container.build_hash' => 'ER9Jhtn',
    'container.build_id' => '1161d828',
    'container.build_time' => 1584395601,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerER9Jhtn');
